---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ansible-ee-tt
spec:
  params:
    - name: gitrevision
      description: The git revision (id)
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations:
        labels:
          tekton.dev/pipeline: ansible-builder
        generateName: ansible-ee-triggered-run-
      spec:
        params:
        - name: ANSIBLE_BUILDER_IMAGE
          value: >-
            registry.redhat.io/ansible-automation-platform-24/ansible-builder-rhel9:latest
        - name: NAME
          value: image-registry.openshift-image-registry.svc:5000/aap-tekton-pipeline-sumi/sample-ee
        - name: TAG
          value: $(tt.params.gitrevision)
        - name: TLSVERIFY
          value: 'false'
        - name: git-url
          value: $(tt.params.gitrepositoryurl)
        - name: git-revision
          value: $(tt.params.gitrevision)
        pipelineRef:
          name: ansible-builder
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
        - name: ee-repo
          persistentVolumeClaim:
            claimName: ansible-builder-pvc
