---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: ansible-ee-tt
spec:
  params:
    - name: gitrevision
      description: The git revision (id)
    - name: short-id
      description: truncated commit id
    - name: gitrepositoryurl
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        annotations:
        labels:
          tekton.dev/pipeline: ansible-builder
        generateName: ansible-ee-triggered-run-
      spec:
        params:
        - name: ANSIBLE_BUILDER_IMAGE
          value: >-
            registry.redhat.io/ansible-automation-platform-21/ansible-builder-rhel8:1.0.1-47
        - name: NAME
          value: quay.io/jtudelag/ansible-ee-test
        - name: TAG
          value: $(tt.params.short-id)
        - name: TLSVERIFY
          value: 'false'
        - name: git-url
          value: $(tt.params.gitrepositoryurl)
        - name: git-revision
          value: $(tt.params.gitrevision)
        - name: short-git-revision
          value: $(tt.params.short-id)
        pipelineRef:
          name: ansible-builder
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
        - name: ee-repo
          persistentVolumeClaim:
            claimName: ansible-builder-pvc